### ISSUE TITLE
Specifying the order in which minified content is generated

### ISSUE THREAD

**Issue by jaw-sh** [DevFactoryCH/minify#10]
The way that files are minified in a directory is a mystery to me. I think it prioritizes subdirectories first which is a problem.

If my directory structure is this:
- /js/
- /js/app/
- /js/app/`[multiple javascript files for my site depending on libraries]`
- /js/vendor/
- /js/vendor/lib/`[jquery and modernizr]`
- /js/vendor/plugin/`[jquery plugins]`

I have no way of specifying order. I need /vendor/lib/ first, /vendor/plugin/ second, and then /app/.

The only way to accomplish this is to add 3 different `Minify` instances which will create 3 requests.

**Comment by niranjan94** [comment]
+1 .. Same problem here...

**Comment by sirsquall** [comment]
Hi,

The package will loop into the directory and contruct an array for each file with the good extension, and at the end he will do a `rsort` on the array, and after he will process the file.

http://php.net/manual/fr/function.rsort.php 

If you want to change feel free to do a pull request.

**Comment by niranjan94** [comment]
@sirsquall Curious to know why you went with reverse sorting ?

**Comment by niranjan94** [comment]
#15 might be useful.

**Comment by sirsquall** [comment]
Merged
