### ISSUE TITLE
Problem with UTF chars

### ISSUE THREAD

**Issue by Pyton** [DevFactoryCH/minify#16]
On my minified JS file I have wrong statement:
`varπ=Math.PI,ε=1e-6,d3_radians=π/ 180,d3_degrees=180 /π;`

Oryginal line:
`var π = Math.PI, ε = 1e-6, d3_radians = π / 180, d3_degrees = 180 / π;`

Laravel 5.1
devfactory/minify 1.0.1

**Comment by sirsquall** [comment]
This package is juste a wrapper for this one : 
https://github.com/tedious/JShrink

You should poste your issues to they repo.
