### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by JoshuaNovak919** [DevFactoryCH/minify#17]
I tried using this package, but it doesn't seem to work. It loads the files fine locally, but when I take `local` out of `ignore_environments`, nothing happens. It does not build the files that it should. Do I need to run a command to have it build the files?

**Comment by JoshuaNovak919** [comment]
Actually, I got it to work. Seems that you have to manually make the `css/builds` and `js/builds` folders to get it to work.

**Comment by sirsquall** [comment]
Yes you have to create the folder
