### ISSUE TITLE
Config parameter for filename hash type

### ISSUE THREAD

**Issue by tobi76** [DevFactoryCH/minify#18]
Hi,
currently we have problems using this nice minify implementation on multiple servers. The deployment process sets different timestamps to public/assets files, so the filename hash generated by filename and mtime is different on balanced servers. If there is no sticky loadbalancer session, the laravel deployment try to open unknown hash-filenames on the other servers.
It would be great, if there is an config parameter to define the hash-building. Possibly only use filenames, or filenames with timestamps (currently), or other thinks.
What do you think about that?

Thanks,
Tobias

**Comment by sirsquall** [comment]
Hi,

Yes is a good idea, unfornatly I didn't have so much time to do that. 

So feel free to do a pull request and I will merge it.

Thanks

**Comment by tobi76** [comment]
Hi sirsquall,

as you can see, I add an pull request (https://github.com/DevFactoryCH/minify/pull/19).

Thanks,
Tobi

**Comment by sirsquall** [comment]
I have merged manualy and fix the test but it's ok now in the version 1.0.3

Thanks you
