### ISSUE TITLE
Issue when used on angular-material.js

### ISSUE THREAD

**Issue by binuud** [DevFactoryCH/minify#26]
When minify is being used, and angular-material.js is getting minified.

The line 21481 of angular-material.js ( v1.0.4)
     var urlRegex = /[-a-zA-Z0-9@:%_+.~#?&//=]{2,256}.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_+.~#?&//=]*)?/i;

Gets compressed as     

var urlRegex = /[-a-zA-Z0-9@:%_+.~#?&//=]{2,256}.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_+.~#?&

It is skipping the second instance of '//='

**Comment by sirsquall** [comment]
This package is juste a wrapper for this one : 
https://github.com/tedious/JShrink

You should poste your issues to they repo.
