### ISSUE TITLE
What exactly are "custom attributes"?

### ISSUE THREAD

**Issue by Quezler** [DevFactoryCH/minify#28]
```
        // add custom attributes
        {!! Minify::javascript(array('/js/jquery.js', '/js/jquery-ui.js'), array('bar' => 'baz')) !!}
```

Ive been looking through the sourcecode, but i coudn't quite figure out what the purpose is of "custom attributes", any help?

**Comment by sirsquall** [comment]
You can have a look to this ticket : https://github.com/DevFactoryCH/minify/issues/18

**Comment by Quezler** [comment]
i'm sorry, i read #18, but i still can't make up on how to put `array('bar' => 'baz')` to use.

**Comment by sirsquall** [comment]
It's the second parameter in the method, the attributes.

`{!! Minify::javascript('/js/jquery.js', array('bar' => 'baz')) !!}`

**Comment by Quezler** [comment]
i know, but what are some possible values for them? `bar => baz` is a little to vague for me.

**Comment by sirsquall** [comment]
Is simply the attribute of the html script tag:
`<script src="file" bar="baz"></script>`

http://www.w3schools.com/tags/tag_script.asp

**Comment by Quezler** [comment]
ah, of cource!

my first thought was that you could pass php variables to javascript or something, but now i know ;)

(i don't see any relation between this and #18 though?)

**Comment by sirsquall** [comment]
Oups no one, sorry for that!
