### ISSUE TITLE
The last Slash is incorrect

### ISSUE THREAD

**Issue by Codename-Beast** [DevFactoryCH/minify#3]
Sorry my systm have a error

**Comment by sirsquall** [comment]
Could you tell me more ?

**Comment by Codename-Beast** [comment]
Your tool added worng slash on the end
![bug](https://cloud.githubusercontent.com/assets/7310030/6229849/067e104a-b6bb-11e4-999b-e180ec522fb5.PNG)

**Comment by sirsquall** [comment]
And could you show me the code you have used in your template ?

**Comment by Codename-Beast** [comment]
![coden](https://cloud.githubusercontent.com/assets/7310030/6231361/89074080-b6c6-11e4-9b1c-eece5806e1f0.PNG)

**Comment by sirsquall** [comment]
Thanks I will look

**Comment by sirsquall** [comment]
Could you try that : 

```
{!! Minify::stylesheetDir('/themes/frontend/css/') !!}
```

or

```
{!! Minify::stylesheetDir('/themes/frontend/css/')->withFullUrl() !!}
```

I have tried but I cannot reproduce, in witch OS are you ? and can you show me your `minify.config.php`?

And when the file are minified have you the same error ?
