### ISSUE TITLE
Static syntax in blade examples

### ISSUE THREAD

**Issue by bingalls** [DevFactoryCH/minify#30]
Examples in README.md call `Minify::javascript()` & stylesheet() statically, but these are defined as non-static functions in src/Minify.php. If these cannot be rewritten as static functions, then please provide examples of how to get & pass required $config & $environment args into `new Devfactory\Minify\Minify($cfg, $env).stylesheet([])` for a correct syntax.
Not sure, if future versions of PHP will require such correctness, or other problems might ensue.

**Comment by sirsquall** [comment]
This package is only for laravel, and laravel use the Facade design patern. This class do not need to be updated.

Please follow the installation step, include the facade in the config and the service provider and everything will work well.

Thanks
