### ISSUE TITLE
Inline javascript/css

### ISSUE THREAD

**Issue by dalibor-sojic** [DevFactoryCH/minify#31]
This is more feature request then issue. 

It would be nice if it can minify (save to file) inline javascript/css (passed as string) , ex:
`Minify::javascript("<script>alert('x')</scirpt>")`

**Comment by sirsquall** [comment]
Sorry for the delay, yes it could be nice, I don't have time to do this but if you want you can contribute to the project, it will be really appreciate 

Thanks
Alcindo
