### ISSUE TITLE
[Question] What about multiple build paths?

### ISSUE THREAD

**Issue by mahony0** [DevFactoryCH/minify#32]
I'm using this library and it's useful for most aspects. I separated public assets for both desktop and mobile. Example folder structure:
- public
  - webv1
    - css
      - builds
    - js
      - builds
    - vendor
  - mobilev1
    - css
      - builds
    - js
      - builds
    - vendor

So I need multiple config options for css_build_path, css_url_path, js_build_path and js_url_path. Now I'm using like this but it's not suitable for my situation:

> 'css_build_path' => '/webv1/css/builds/'
> 'css_url_path' => '/webv1/css/builds/'
> 
> 'js_build_path' => '/webv1/js/builds/'
> 'js_url_path' => '/webv1/js/builds/'

Is there a logical way to achieve this?

**Comment by sirsquall** [comment]
Sorry for the delay, yes it could be nice, I'm afraid that we do not have any logical way to do that for the moment. 

I don't have time to do this but if you want you can contribute to the project, it will be really appreciate. 

Thanks
Alcindo
