### ISSUE TITLE
Minify does not work

### ISSUE THREAD

**Issue by tuyenlaptrinh** [DevFactoryCH/minify#6]
I test in laravel 5 but after render i see Minify doesn't change anything
![image](https://cloud.githubusercontent.com/assets/7567800/7361741/611c463a-ed88-11e4-89a3-f86fa98f9d1e.png)
![image](https://cloud.githubusercontent.com/assets/7567800/7361758/7a00e3ae-ed88-11e4-805f-9b42df481133.png)
I checked in css/builds/ path but don't see any file
Please help me

**Comment by markcameron** [comment]
Make sure that you have run `php artisan vendor:publish`, and then in `config/minify.config.php` check the `ignore_environments` option... you probably have your environment set to `local`, and it won't build the minified files unless you change the environment in your `.env` file.

**Comment by tuyenlaptrinh** [comment]
Ok. I fixed.
