### ISSUE TITLE
Solution for image, font, etc in javascript file and style file

### ISSUE THREAD

**Issue by tuyenlaptrinh** [DevFactoryCH/minify#7]
Minify working good.
But i have trouble with include any file in css file, js file.
Have solution for this problem?
Route?
htaccess?

**Comment by markcameron** [comment]
Well you should place the build folder in the same folder as your cs/js folders... you get something like this:

```
assets/
|-css/
|-js/
|-img/
|-fonts/
|-build/
```

Then you reference in your css, the fonts and images as being `../fonts/font.eof` and `../img/image.png` and the folder structure holds.
