### ISSUE TITLE
Minification breaks bootstrap's glyphicons

### ISSUE THREAD

**Issue by Binternet** [DevFactoryCH/minify#9]
When i'm not minifying my stylesheet, glyphicons works great. when I'm running the Minify::stylesheet, it breaks them...

**Comment by sirsquall** [comment]
Hello,

This package it's only a wrapper for laravel, the minify is rendered by this package:
https://github.com/natxet/CssMin

You shoud post you issue in their repository.

**Comment by Binternet** [comment]
Will do. thanks.
